GET https://jsonplaceholder.typicode.com/todos/
Accept: application/json

fetch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => response.json())
  .then(json => console.log(json))

<> 2022-05-07T105712.200.json
<> 2021-10-07T165204.200.json
<> 2021-10-07T165131.200.json
###
GET https://arni.stage-arms.bank24.int/api/v1/agent_check/report/?agent__inn=7287593553
Accept: application/json

###
